export const USER_LOGIN = 'USER_LOGIN';

export const ON_ANSWER = 'ON_ANSWER';

export const CHANGE_DIFFICULTY = 'CHANGE_DIFFICULTY';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const CHANGE_TYPE = 'CHANGE_TYPE';
